### ISSUE TITLE
Asteroids game points explanation

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#68] opened 2016-05-16 18:00 UTC
Bigger font for "How it works" section - both for points scored for each object and the text. Make entire 'How It Works" section larger?

**Comment by TAGraves** [comment] 2016-05-16 18:01
Closing this as it looks like a duplicate of https://github.com/YMCACOLUMBUS/activescience-issues/issues/18

**Closed as completed by TAGraves** 2016-05-16 18:01 UTC
