### ISSUE TITLE
Level 7 Bonus Question graphs/ correct answer

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#47] opened 2016-05-06 18:33 UTC
Level 7- On this screen, if there are multiple days with the same distance there is no option to select multiple days that I traveled the farthest. If I choose Day 5 or Day 6, two of the days with 5 miles (the farthest distance but there are 2 other days that I also did 5 miles) it says that my answer is incorrect and it does not allow me to move forward. If I choose Day 4, another day with 5 miles, I have to tap the "go" button multiple times and it lets me advance to the game.

Level 9 - Same issue as Level 7. Cannot move forward

**Comment by TAGraves** [comment] 2016-05-06 20:12
Duplicate of https://github.com/YMCACOLUMBUS/activescience-issues/issues/32

**Closed as completed by TAGraves** 2016-05-06 20:12 UTC
