### ISSUE TITLE
Grade 1 + 2 Game unlocked at end of level 1

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#62] opened 2016-05-10 15:19 UTC
Level 1--When you complete the level 1 and it says “you have unlocked the game”, then you click next and it goes to the Congrats you have completed level 1. When do they get a chance to play the game?

**Comment by TAGraves** [comment] 2016-05-10 18:18
This is a duplicate of #41, so closing.

**Closed as completed by TAGraves** 2016-05-10 18:18 UTC
